import { useState, useEffect } from 'react'
import { useWorkflow } from '../contexts/WorkflowContext'
import AgentAvatar from '../components/AgentAvatar'
import { 
  FileText, 
  Download, 
  ArrowRight, 
  ChevronDown, 
  ChevronUp,
  ExternalLink
} from 'lucide-react'
import ReactMarkdown from 'react-markdown'
import api from '../lib/api'

const ResultsPage = () => {
  const [outputs, setOutputs] = useState({})
  const [loading, setLoading] = useState(true)
  const [expandedOutput, setExpandedOutput] = useState(null)
  const [generatingPdf, setGeneratingPdf] = useState(false)
  const [pdfUrl, setPdfUrl] = useState(null)
  
  const { 
    workflowState, 
    updateWorkflowState,
    nextPhase
  } = useWorkflow()
  
  // Fetch outputs
  useEffect(() => {
    const fetchOutputs = async () => {
      try {
        const data = await api.getOutputs()
          setOutputs(data)
        }
      } catch (error) {
        console.error('Failed to fetch outputs:', error)
      } finally {
        setLoading(false)
      }
    }
    
    fetchOutputs()
  }, [])
  
  // Generate PDF report
  const generatePdfReport = async () => {
    setGeneratingPdf(true)
    try {
      const response = await api.generateReport('comprehensive')
      
      setPdfUrl(response.download_url)
    } catch (error) {
      console.error('Failed to generate PDF:', error)
    } finally {
      setGeneratingPdf(false)
    }
  }
  
  // Continue to dashboard
  const continueToDashboard = () => {
    nextPhase()
  }
  
  // Toggle output expansion
  const toggleOutput = (outputKey) => {
    if (expandedOutput === outputKey) {
      setExpandedOutput(null)
    } else {
      setExpandedOutput(outputKey)
    }
  }
  
  return (
    <div className="max-w-4xl mx-auto">
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-gray-900 mb-2">
          Your Startup Plan
        </h1>
        <p className="text-gray-600">
          Review the outputs generated by your AI team
        </p>
      </div>
      
      {loading ? (
        <div className="bg-white rounded-lg shadow-sm border p-8 text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600 mx-auto mb-4"></div>
          <p className="text-gray-600">Loading outputs...</p>
        </div>
      ) : (
        <>
          <div className="bg-white rounded-lg shadow-sm border p-6 mb-8">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-xl font-semibold text-gray-900">
                Generated Outputs
              </h2>
              
              <button
                onClick={generatePdfReport}
                disabled={generatingPdf}
                className="flex items-center px-4 py-2 bg-primary-600 text-white rounded-md hover:bg-primary-700 disabled:opacity-50"
              >
                {generatingPdf ? (
                  <>
                    <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                    Generating...
                  </>
                ) : (
                  <>
                    <Download className="h-4 w-4 mr-2" />
                    Generate Report
                  </>
                )}
              </button>
            </div>
            
            {pdfUrl && (
              <div className="mb-6 p-4 bg-green-50 rounded-md">
                <div className="flex items-center justify-between">
                  <div className="flex items-center">
                    <FileText className="h-5 w-5 text-green-600 mr-2" />
                    <span className="text-green-800 font-medium">Report generated successfully!</span>
                  </div>
                  <a
                    href={pdfUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center px-3 py-1 bg-green-600 text-white text-sm rounded-md hover:bg-green-700"
                  >
                    <ExternalLink className="h-4 w-4 mr-1" />
                    View Report
                  </a>
                </div>
              </div>
            )}
            
            <div className="space-y-4">
              {Object.entries(outputs).length === 0 ? (
                <p className="text-gray-600 text-center py-8">No outputs available yet</p>
              ) : (
                Object.entries(outputs).map(([outputKey, outputData]) => (
                  <div key={outputKey} className="border rounded-lg overflow-hidden">
                    <div 
                      className="flex items-center justify-between p-4 cursor-pointer hover:bg-gray-50"
                      onClick={() => toggleOutput(outputKey)}
                    >
                      <div className="flex items-center">
                        <AgentAvatar agent={outputData.agent} size="sm" />
                        <div className="ml-3">
                          <h3 className="font-semibold text-gray-900">
                            {outputData.agent} Output
                          </h3>
                          <p className="text-xs text-gray-500">
                            Generated on {new Date(outputData.timestamp).toLocaleString()}
                          </p>
                        </div>
                      </div>
                      
                      <div className="flex items-center">
                        <span className="text-sm text-gray-600 mr-2">
                          {expandedOutput === outputKey ? 'Hide' : 'Show'}
                        </span>
                        {expandedOutput === outputKey ? (
                          <ChevronUp className="h-5 w-5 text-gray-500" />
                        ) : (
                          <ChevronDown className="h-5 w-5 text-gray-500" />
                        )}
                      </div>
                    </div>
                    
                    {expandedOutput === outputKey && (
                      <div className="p-4 border-t bg-gray-50">
                        <div className="prose prose-sm max-w-none">
                          <ReactMarkdown>
                            {typeof outputData.data === 'string' 
                              ? outputData.data 
                              : JSON.stringify(outputData.data, null, 2)}
                          </ReactMarkdown>
                        </div>
                      </div>
                    )}
                  </div>
                ))
              )}
            </div>
          </div>
          
          <div className="flex justify-center">
            <button
              onClick={continueToDashboard}
              className="flex items-center px-6 py-3 bg-primary-600 text-white font-medium rounded-md hover:bg-primary-700"
            >
              Continue to Dashboard
              <ArrowRight className="h-5 w-5 ml-2" />
            </button>
          </div>
        </>
      )}
    </div>
  )
}

export default ResultsPage